# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35c550cec8d5d1ee9353ae74c6e43f0deb0bf05f51a793e4545cf3edbe74395c45f439ccf14dd2c3f121285232549076f96fa78dfeb56447e2024baf2a7e39a

test:
  secret_key_base: efb9564cc37cef9624a6d1ad6623d07962c903a9360c719aa3290fc56a7807c55dc7e235bd6755d8ba8f0cdf6f0fbac8facddf78402375534196dcbe8950deb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
